//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveApp.Resources.Messages.fr", typeof(Messages_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Travaux de sauvegarde actuels ---.
        /// </summary>
        public static string CurrentJobsTitle {
            get {
                return ResourceManager.GetString("CurrentJobsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez le numéro du travail à exécuter (ex: 1) : .
        /// </summary>
        public static string EnterJobNumber {
            get {
                return ResourceManager.GetString("EnterJobNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélection invalide..
        /// </summary>
        public static string InvalidSelection {
            get {
                return ResourceManager.GetString("InvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Créer un travail de sauvegarde.
        /// </summary>
        public static string MenuCreate {
            get {
                return ResourceManager.GetString("MenuCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Exécuter les sauvegardes.
        /// </summary>
        public static string MenuExecute {
            get {
                return ResourceManager.GetString("MenuExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Quitter.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Lister les travaux.
        /// </summary>
        public static string MenuList {
            get {
                return ResourceManager.GetString("MenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Menu EasySave ---.
        /// </summary>
        public static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Nouveau Travail de Sauvegarde ---.
        /// </summary>
        public static string NewJobHeader {
            get {
                return ResourceManager.GetString("NewJobHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom : .
        /// </summary>
        public static string PromptName {
            get {
                return ResourceManager.GetString("PromptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répertoire Source : .
        /// </summary>
        public static string PromptSource {
            get {
                return ResourceManager.GetString("PromptSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répertoire Cible : .
        /// </summary>
        public static string PromptTarget {
            get {
                return ResourceManager.GetString("PromptTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type (1: Complète, 2: Différentielle) : .
        /// </summary>
        public static string PromptType {
            get {
                return ResourceManager.GetString("PromptType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez une option : .
        /// </summary>
        public static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
    }
}
